FROM container-registry.oracle.com/os/oraclelinux:8-slim
ARG BINARY
ARG VERSION

RUN microdnf install -y tar which bzip2 &&\
    microdnf clean all &&\
    rm -rf /var/cache/yum/*

ADD ${BINARY} /usr/local/bin/${BINARY}

RUN test -d /LICENSES || ln -s /usr/share/licenses /LICENSES
ADD LICENSE /LICENSES/kubernetes-${VERSION}/LICENSE
ADD THIRD_PARTY_LICENSES.txt /LICENSES/kubernetes-${VERSION}/THIRD_PARTY_LICENSES.txt
